
# This script summarizes results from computation of displacement distances,
#  as provided on output files from execution of  allDistances.R

# Results are written to  'outFile'



# --- User's specifications start here ---

# Distance bounds for categories over which individual grid cell
#  distances will be counted:
limVal  <- c(0,20,40,60,80,100,120,140,160,180,200)

# Name of output file:
outFile <- "distance_distro.dat"

# --- User's specifications end here ---



#  'outLine'  will store lines to be written to the output file.
lineNo  <- 0
outLine <- vector(mode="character")

for (edgeNo in 1:2) {

    lineNo <- lineNo + 1
    outLine[lineNo] <- paste(" *** RESULTS for edge no.",edgeNo,"***")

    # Read file with distance results, generated by  allDistances.R
    inFile <- paste("distance_all_edge",edgeNo,".dat", sep="")
    values <- scan(inFile)
    nVal   <- length(values)

    # Count no of displacement distances for each interval,
    #   starting with   [ limVal [1],     limVal [2]   >
    #   ending   with   [ limVal[nLim-1], limVal[nLim] >
    # one output line for each interval:
    nLim   <- length(limVal)
    vMax   <- limVal[1]
    for (n in 2:nLim) {
        vMin   <- vMax
        vMax   <- limVal[n]
        indx   <- which(values >= vMin & values < vMax)
        lineNo <- lineNo + 1
        outLine[lineNo] <- paste("Range ",vMin,"-",vMax,", no.:",length(indx),
                                 ", fraction:",length(indx)/nVal)
    }

    # Also provide minimum, maximum displacements, on separate
    #  output lines:
    lineNo <- lineNo + 1
    outLine[lineNo] <- paste("Minimum distance:",min(values))
    lineNo <- lineNo + 1
    outLine[lineNo] <- paste("Maximum distance:",max(values))

}

# Write reaults to  outFile
cat(outLine, file=outFile, sep="\n")

quit("no")
